### ISSUE TITLE
Pyspark: Provide solutions for smaller tasks

### ISSUE THREAD

**Issue by AdamProbert** [madetech/data-101#12]
Feedback from Matthew Daley:

> In terms of the pyspark, it would be helpful to have 'task' > expected output for the mini-tasks for people to know that they're doing it correctly, but other than that I could get going with a mix of previous python syntax knowledge, docs and google. It depends on how this will be used, e.g. academy, transitioning for engineers with limited python knowledge or someone with decent python background.

**Comment by tf75** [comment]
To make the pyspark tutorial more simple and basic, going through very basic path and then encourage further research
