### ISSUE TITLE
Data-101 for non-techies

### ISSUE THREAD

**Issue by AdamProbert** [madetech/data-101#9]
We've had some requests for adding documentation on high level data tutorials to be used by the people team, hiring, scheduling etc. I think this is a really great idea, though a challenging one.
Making a note here for visibility, please add comments with ideas!

**Comment by tf75** [comment]
Cheat sheet - infographic, miro board

**Comment by AdamProbert** [comment]
Example questions to answer:
- What is etl/elt?
- What is cloud? AWS Azure
- Why do companies need data platforms?
- What's this bronze, silver, gold bucket stuff?
- Streaming vs batch?
- Spark, pyspark? are these the same thing?

**Comment by tf75** [comment]
Not needed for the immediate future
